# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "test release"

on:
  push:
  - master
  - main


jobs:
  test:
    name: "Test"
    runs-on: "ubuntu-latest"
        strategy:
            matrix:
                php: [8.4, 8.3]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - run: echo "${{ github.token }}"
