name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        stuff:
          - one
          - two
          - three

    steps:
      - run: echo ${{ secrets.GITHUB_TOKEN }} | rev

      - run: sleep 600
